### PR TITLE
fix bug when create direct room

### PR DESCRIPTION
**Pull request by bagvand**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content
before this fix you can not create direct chat.

### CODE REVIEW

**Comment by bmarty** [comment]
Hello @bagvand thanks for the proposal. Can you add more context about the issue you are encountering (without your fix)?

**Comment by bagvand** [comment]
Hi @bmarty 
when we are using `awaitTransaction` then transaction will be blocked and nothing happen after `awaitTransaction`.
maybe we have starvation in transaction when using `awaitTransaction`.

**Comment by bagvand** [comment]
Steps to repro:
1 - Go to "Start Chat"
2 - Choose someone you haven't chatted with him before.
3- Loading will be shown and no dismiss(starvation in transaction of saving user profile)

**Comment by bmarty** [comment]
(Thanks. I do not repro your issue here)

**Comment by bagvand** [comment]
It will happen when selecting someone in contacts book.

**Comment by bmarty** [comment]
OK, thanks. The issue has been fixed by https://github.com/vector-im/element-android/issues/7870, which is in Element 1.5.18.

**Pull request closed without merging**
