### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by chagai95**
### Pull Request Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Pull request is based on the develop branch
- [ ] Pull request updates [CHANGES.md](https://github.com/vector-im/element-android/blob/develop/CHANGES.md)
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by bmarty** [comment]
Hello, thanks for this typo fix, can you sign it off please? See https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off

**Comment by chagai95switzerland** [comment]
Sorry...
Signed-off-by: Chagai Friedlander <chagai95@gmail.com>

**Comment by bmarty** [comment]
Thanks. Can you fix the typo everywhere (I see 2 other place, line 5 (the link) and line 25 in this file please?

**Comment by chagai95** [comment]
I'll get to it soon hopefully....

**Comment by bmarty** [comment]
I'll do it

**Comment by chagai95** [comment]
Sorry...

**Comment by bmarty** [comment]
np :)

**Pull request closed without merging**
