### PR TITLE
[issue-2610] implement setting to override nick color

### PR DESCRIPTION
**Pull request by mitchnull**
Implement issue #2610 

- allow changing the nick color by clicking the "Override color" menu item
  in the room  member detail page.
- the override-color can be specified as a hex string (#rrggbb) or as palette
  index (2)
- entering an invalid color code or leaving the field blank reverts to
  the default hash-based nick color
- the setting is stored in `account_data` as `im.vector.setting.override_colors`

- future improvements / notes:
  - replace the text-based color entry with a proper color picker dialog
  - ~make the feature more discoverable~ [added menu item under More]
  - the color change listener is now in AppStateHandler, not sure if this is
    the best place
  - implement override color support in element-web / element-desktop, too

Signed-off-by: Péter Radics <mitchnull@gmail.com>

Screenshot:
Screenshot_20210101-003601_Element-override-color

### Pull Request Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [x] Pull request is based on the develop branch
- [x] Pull request updates [CHANGES.md](https://github.com/vector-im/element-android/blob/develop/CHANGES.md)
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by mitchnull** [comment]
Screenshot_20210101-003601_Element-override-color

**Comment by mitchnull** [comment]
Is the build farm broken?  The failing builds run without problems locally.

**Comment by bmarty** [comment]
Since the change of color is only client side and shared across user's device, I do not see a reason to not merge this PR.
I have quickly read the discussion in https://github.com/vector-im/element-web/issues/11816.

TODO:

- changelog has to be moved to a dedicated file
- "the color change listener is now in AppStateHandler, not sure if this is the best place". Maybe better in a ViewModel used by the HomeActivity
- fix conflict

**Comment by bmarty** [comment]
Will handle the remaining work on my branch.

**Comment by mitchnull** [comment]
> Will handle the remaining work on my branch.

thanks for picking this up!

**Pull request merged**
