### PR TITLE
Convert PushersService to suspend functions

### PR DESCRIPTION
**Pull request by Dominaezzz**
Signed-off-by: Dominic Fischer <dominicfischer7@gmail.com>

### Pull Request Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [x] Pull request is based on the develop branch
- [ ] Pull request updates [CHANGES.md](https://github.com/vector-im/element-android/blob/develop/CHANGES.md)
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Review by bmarty — APPROVED** [review]
This one is perfect, thanks!

**Comment by bmarty** [comment]
Sorry, actually the CI is not happy :/

**Review by bmarty — CHANGES_REQUESTED** [review]
Can you check what the CI is reporting please?

**Comment by Dominaezzz** [comment]
Any idea why there's no auto-complete in this file `im.vector.app.gplay.features.settings.troubleshoot.TestPushFromPushGateway`?

**Comment by bmarty** [comment]
> Any idea why there's no auto-complete in this file `im.vector.app.gplay.features.settings.troubleshoot.TestPushFromPushGateway`?

This file is compiled only if you select one of the `gplay` build variants. You are probably compiling the variant `fdroidDebug`. In this case, no completion and no live compilation are available. If you select `gplayDebug` and sync the IDE it will fix that.

**Comment by bmarty** [comment]
Thanks for the update, I'll fix the ktlint issue on develop

**Comment by bmarty** [comment]
Cleanup in https://github.com/vector-im/element-android/commit/e4e13aaa9790f154b6032b05e62907901d72d4a4

**Pull request merged**
