### PR TITLE
Make Space creation screens more consistent

### PR DESCRIPTION
**Pull request by noantiq**
Changed the UI as described in #3942:

- Gave titles the same font size
- Removed the duplicate "Spaces are a new way [...]"
- Have "You can change this later" on both screens
- Have title and description on top of each screen

I did not center the header title ("Create a space" / "Your private space") as suggested since the header titles are usually left aligned throughout the app if I am not mistaken.

See:

**EDIT from bmarty: adding a table to wrap the screenshots**

|Create space|Create private space|
|-|-|
|Screenshot_20220131_134640|Screenshot_20220131_134841|

### Pull Request Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- ~~[ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)~~

### CODE REVIEW

**Review by bmarty — APPROVED** [review]
Thanks a lot for your PR!
LGTM, will need design approval from @niquewoodhouse

**Comment by artevaeckt** [comment]
By looking at the screenshots again I just now noticed I missed a thing. The string create_spaces_make_sure_access ("Make sure the right people have access to %s. You can change this later." on the second screen) needs an edit too.

I would get rid of the last sentence. I looked at the [contribution guide](https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#editing-existing-strings) but am not quite sure if I should just edit the string or create a new one instead.

**Comment by bmarty** [comment]
@artevaeckt you can edit the string, only the original one, so [this one](https://github.com/vector-im/element-android/blob/main/vector/src/main/res/values/strings.xml#L3488), since it does not change the meaning. The time the translations come from Weblate there will be a duplicated sentence, but this is not a big deal.

Since you will be in the area, can you add a comment to mark the string `create_spaces_type_header` for deletion? Details are in the contributing doc you've just read :)

Thanks!

**Comment by bmarty** [comment]
(and good catch by the way!)

**Review by bmarty — APPROVED** [review]
Perfect thanks!

**Review by niquewoodhouse — APPROVED** [review]

**Pull request merged**
