### PR TITLE
Send voice message should not be allowed during a voice broadcast recording

### PR DESCRIPTION
**Pull request by yostyle**
#7895

### CODE REVIEW

**Comment by jmartinesp** [comment]
Should we also consider the case when the voice broadcast is paused, you start a voice message and lock it so it keeps recording, then resume the broadcast? I think both recordings will be running at the same time.

https://user-images.githubusercontent.com/480955/213427686-303e9566-64b6-4663-a382-01c9aed68bc2.mov

**Comment by giomfo** [comment]
> Should we also consider the case when the voice broadcast is paused, you start a voice message and lock it so it keeps recording, then resume the broadcast? I think both recordings will be running at the same time.

Yes we should block voice message even when voice broadcast is paused

**Review by jmartinesp — CHANGES_REQUESTED** [review]
Based on @giomfo 's comment, I think we need to add some extra checks to prevent voice broadcasts and voice messages from running at the same time.

**Review by jmartinesp — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
