### PR TITLE
Use viewBindingIgnore="true" when we do not need the ViewBinding.

### PR DESCRIPTION
**Pull request by bmarty**
We are using Epoxy and do not need the view binding for the vast majority of list item layouts. Disable their generation and compilation and finally Proguard shrink to have a faster compilation. Let's see if the gain worth it on the CI.

See https://developer.android.com/topic/libraries/view-binding for more details

### CODE REVIEW

**Review by ouchadam — APPROVED** [review]
compiled and works locally fine for me :100: (benchmarking in progress :crossed_fingers: )

**Comment by bmarty** [comment]
I am now wondering if we could use ViewBinding in our VectorEpoxyHolder, or change the bit our arch to be able to do so.

**Comment by ouchadam** [comment]
> I am now wondering if we could use ViewBinding in our VectorEpoxyHolder, or change the bit our arch to be able to do so.

depends if we want to start putting our eggs in the compose basket :thinking:

**Comment by bmarty** [comment]
Ok, thanks for the measures 💯

**Pull request merged**
