### PR TITLE
Added option to record and send videos.

### PR DESCRIPTION
**Pull request by c-andy-proj**
Signed-off-by: Andrea Conalbi <c.andy@aleeas.com>

### Pull Request Checklist

- [X] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [X] Pull request is based on the develop branch
- [X] Pull request updates [CHANGES.md](https://github.com/vector-im/element-android/blob/develop/CHANGES.md)
- [ ] Pull request includes screenshots or videos if containing UI changes
- [X] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

I basically adapted the code of the "camera attachment" for video recording adding a button in the attachments list.
Sorry if I made mistakes, it's my first PR ever.

### CODE REVIEW

**Comment by bmarty** [comment]
Hello @c-andy-proj,

Thanks for the PR, it is working well, and I have no remark on the code. The layout could maybe be improved, this is quite strange to have empty LinearLayout, to center the new "video" icon.

The rendering could maybe be improved, this is what I see on my device:

image

Previously this area was supposed to have the same size than the virtual keyboard, and if the keyboard is open, it is displayed above the keyboard. But now this is like that:

image

This is not ideal.

The icon should be white like the other.

WhatsApp is using a scroll, which is not better I think:

image

I will ask to the design team if they have another idea.

**Comment by heretoenhance** [comment]
Great! I was asking for this in issue #2224, any news on when this will be merged?

**Comment by kojid0** [comment]
Stickers are a bit related to emoji, so I would prefer having them integrated in the emoji picker, just like other messengers do:
82835951-c2131d80-9ec5-11ea-8317-69204392b538 (Handy)

This would solve the issue.

**Comment by bmarty** [comment]
Replaced by #3264

**Pull request closed without merging**
