### PR TITLE
[Ignore] Forcing the screenshot test to fail

### PR DESCRIPTION
**Pull request by ouchadam**
Showcasing how screenshot test failures present themselves  - As artifacts of the `tests.yml` workflow

### CODE REVIEW

**Comment by bmarty** [comment]
The CI seems happy?

**Comment by ouchadam** [comment]
@bmarty yeah it's strange.. I'm looking into it, changing the text to `fail1` fails the test but not `fail` or empty

**Comment by ouchadam** [comment]
> @bmarty yeah it's strange.. I'm looking into it, changing the text to `fail1` fails the test but not `fail` or empty

turns out this was due to the `maxPercentDifference` option defaulting to 0.1%, dropping to 0% catches the changes but has the risk failing due to navigation and status bar pixel rendering quirks (will need to monitor)

**Comment by ouchadam** [comment]
Tests are failing and the artifacts are correctly uploaded https://github.com/vector-im/element-android/actions/runs/3134733720 (can close!)

**Pull request closed without merging**
