### PR TITLE
Identity: Recompute hashes after M_INVALID_PEPPER

### PR DESCRIPTION
**Pull request by AndrewFerr**
When a new pepper is retrieved after an M_INVALID_PEPPER response,
recompute hashes with that pepper, and send those new hashes in the next
lookup attempt instead of reusing the original hashes.

### Pull Request Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [x] Pull request is based on the develop branch
- [x] Pull request updates [CHANGES.md](https://github.com/vector-im/element-android/blob/develop/CHANGES.md)
- [ ] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by AndrewFerr** [comment]
Fixes #2708

**Review by bmarty — APPROVED** [review]
Thanks a lot for this fix!
I'm wondering if there is an other issue in file `IdentityBulkLookupTask.kt` at line 110 (on your branch). We should use `newHashDetailResponse` instead of `hashDetailResponse`. The comment on line 112 (`// Also, what we have in cache is maybe outdated, the identity server maybe now support sha256`) could then be removed. WDYT?

**Comment by bmarty** [comment]
> I'm wondering if there is an other issue in file `IdentityBulkLookupTask.kt` at line 110 (on your branch). We should use `newHashDetailResponse` instead of `hashDetailResponse`. The comment on line 112 (`// Also, what we have in cache is maybe outdated, the identity server maybe now support sha256`) could then be removed. WDYT?

I fixed that on #2714

**Comment by AndrewFerr** [comment]
> > I'm wondering if there is an other issue in file `IdentityBulkLookupTask.kt` at line 110 (on your branch). We should use `newHashDetailResponse` instead of `hashDetailResponse`. The comment on line 112 (`// Also, what we have in cache is maybe outdated, the identity server maybe now support sha256`) could then be removed. WDYT?
> 
> I fixed that on #2714

Thanks for the follow-up fixes! I didn't know the history behind those comments; it was like that when I got there, and the only issue I could find was the one that I fixed. Glad that other fixes were possible too :)

**Pull request merged**
