### PR TITLE
Bugfix/markdown parsing

### LINKED ISSUE #350: Formatted (HTML) messages with markdown features are rendered incorrectly as markdown
When the `formatted_body` field of a `"format": "org.matrix.custom.html"` message contains special markdown characters, they're rendered as markdown instead of as plain text. This could be an actual problem if you escape markdown characters in a message that contains other formatting

<details>
<summary>Exaggerated example</summary>

### Expected rendering
riot web
riot android

### Actual rendering
riot x

### Event source
```json
{
  "type": "m.room.message",
  "sender": "@tulir:maunium.net",
  "content": {
    "msgtype": "m.text",
    "body": "Blank message (or is it? 🤔)",
    "format": "org.matrix.custom.html",
    "formatted_body": "---\n> * # [`RiotX` renders this message ***completely incorrectly***](https://github.com/vector-im/riotX-android/issues/289#issuecomment-510894293)\n---"
  },
  "event_id": "$156295723912295JSonL:maunium.net",
  "origin_server_ts": 1562957239380,
  "unsigned": {
    "age": 52
  },
  "room_id": "!tTIucwUZLRtKnXeurb:matrix.org"
}
```
</details>

<details>
<summary>Non-exaggerated example</summary>

### Expected rendering
riot web
riot android

### Actual rendering
riot x

### Event source
```json
{
  "type": "m.room.message",
  "sender": "@tulir:maunium.net",
  "content": {
    "msgtype": "m.text",
    "format": "org.matrix.custom.html",
    "body": "*less exaggerated example*: \\*\\*stars!**",
    "formatted_body": "<em>less exaggerated example</em>: **stars!**"
  },
  "event_id": "$156295796112315whymM:maunium.net",
  "origin_server_ts": 1562957961390,
  "unsigned": {
    "age": 170
  },
  "room_id": "!jhpZBTbckszblMYjMK:matrix.org"
}
```
</details>

<details>
<summary>Real-life example</summary>

[matrix:room/riotx:matrix.org/event/$15630377604255dZoDF:hacklab.fi](https://matrix.to/#/!tTIucwUZLRtKnXeurb:matrix.org/$15630377604255dZoDF:hacklab.fi?via=matrix.org&via=privacytools.io&via=feneas.org)

This one was a reply sent from RiotX, which had indentation in the fallback format for some reason. The indentation of course turned into a code block because that's what a markdown parser does.

This specific example could be fixed by
* fixing whatever caused the indentation, or
* adding reply rendering to RiotX,

but of course neither of those is a proper fix to this issue.

### Expected rendering
riot web
riot android

### Actual rendering
riot x

### Event source
```json
{
  "content": {
    "body": "><@marmulak:converser.eu> Does the \"black\" theme work for reducing power consumption on oled displays?\n\nYes, the dark theme will reduce power consumption and the black theme will reduce it a bit more",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply>\n               <blockquote>\n                   <a href=\"https://matrix.to/#/!tTIucwUZLRtKnXeurb:matrix.org/$1563036634937vaAEg:converser.eu\">In reply to</a>\n                   <a href=\"https://matrix.to/#/@marmulak:converser.eu\">@marmulak:converser.eu</a>\n                   <br />\n                   <p>Does the &quot;black&quot; theme work for reducing power consumption on oled displays?</p>\n\n               </blockquote>\n           </mx-reply>\n           Yes, the dark theme will reduce power consumption and the black theme will reduce it a bit more",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$1563036634937vaAEg:converser.eu"
      }
    },
    "msgtype": "m.text"
  },
  "event_id": "$15630377604255dZoDF:hacklab.fi",
  "origin_server_ts": 1563037760897,
  "sender": "@vurpo:hacklab.fi",
  "type": "m.room.message",
  "unsigned": {
    "age": 630
  },
  "room_id": "!tTIucwUZLRtKnXeurb:matrix.org"
}
```
</details>

### LINKED ISSUE #1375: Strange formatted message handling
riotX shows strange display behavior with formatted messages.

# Expected behavior:
if a message contains `"format":"org.matrix.custom.html" `and a `formatted_body` field, the contents of the `formatted_body` are displayed.
# Current behavior:
if the `body` field contains a code block in markdown, the body field is parsed as markdown and displayed instead of the formatted body(markdown parsing only if it is a `org.matrix.custom.html` message). 

Furthermore, when the html body is used, the pre/code block is not properly formatted(see third example in the screenshots below).

screenshots:

Expected message display(riot desktop):
2020-05-16-184925_456x240_scrot

Riotx display:
2020-05-16-185301_1074x388_scrot

Message sources:
```
  "content": {
    "msgtype": "m.text",
    "format": "org.matrix.custom.html",
    "body": "```\ncode body 1",
    "formatted_body": "<pre><code>html body 1</code></pre>"
  },
```

```
  "content": {
    "msgtype": "m.text",
    "format": "org.matrix.custom.html",
    "body": "normal body 2",
    "formatted_body": "<pre><code>html body 2</code></pre>"
  },
```

```
  "content": {
    "body": "```\ncode body 3",
    "msgtype": "m.text"
  },
```
@tulir identified the source for the issue [here](https://github.com/vector-im/riotX-android/blob/5fa247a0c5c02e34ea2caf6b68e458b115eb21ce/vector/src/main/java/im/vector/riotx/features/home/room/detail/timeline/factory/MessageItemFactory.kt#L356)

Our troubleshooting discussion in the #riotx room can be found [here](https://matrix.to/#/!gGkYcJLTzcNrfERksd:matrix.org/$a2pBDO4VhlGZyxQyM2KJRGUeMC6aIk5PbYuwSyghwAI?via=matrix.org&via=privacytools.io&via=tchncs.de)

Tested version: 0.19.0 [40019000] (F-be9393fa)

### LINKED ISSUE #1939: Editing message forgets line breaks and markdown
**Describe the bug**
When sending a message with line breaks and/or markdown markup and taping the *edit* option, those line breaks and markdown markups disappear, resulting in very odd messages.

**To Reproduce**
1. Go to a sent message
2. Click on "edit"
3. The line breaks and markdown have disappeared

**Expected behavior**
When editing a message, all of its line breaks and markdown should stay in a editing mode (should appear the *, _, ` and so on).
The line breaks should also stay.

**Screenshots**
Here can be seen the message with markdown (also line breaks, but that's not so evident)
IMG_20200817_154412

Here can be seen how, when editing, the line breaks and markdown is lost.
IMG_20200817_154436

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 4 X
 - OS: /e/OS Android 7 Nougat

**Additional context**
 - 1.0.4 F-Droid
 - matrix.org

### LINKED ISSUE #1982: Markdown Not Rendering
**Describe the bug**
Markdown content is not rendering correctly on the Android version.

**To Reproduce**
1. Enable markdown formatting.
2. Send a markdown formatted message, e.g. 

> \```
> testing
> \```

3. Message does not appear correctly on Element for Android but does appear correctly on web/desktop.

**Expected behavior**
The testing block above should be rendered correctly,

**Screenshots**
Android:
Android

Desktop:
Desktop

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - OS: Android 11 Beta

**Additional context**
 - v1.0.4 from F-Droid
 - Homeserver: munster.dev

I submitted a rageshake shortly before starting this issue.

### PR DESCRIPTION
**Pull request by MexHigh**
This fixes the problem that markdown isn't correctly parsed when the message is composed in the app.
Fixes #350, Fixes #1375, Fixes #1982, Fixes #1939 

### Pull Request Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [x] Pull request is based on the develop branch
- [x] Pull request updates [CHANGES.md](https://github.com/vector-im/element-android/blob/develop/CHANGES.md)
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by absorber** [comment]
Should also fix https://github.com/vector-im/element-android/issues/1939 if I'm not mistaken.

**Comment by MexHigh** [comment]
It does. Thank you.

**Comment by bmarty** [comment]
Thanks for the update

**Comment by tulir** [comment]
This did not fix #350 nor #1375. I don't think it fixed #1939 either, but not completely sure about that

**Comment by bmarty** [comment]
I reopen the issues, which will be closed once when we can confirm that we do not reproduce them

**Comment by MexHigh** [comment]
> This did not fix #350 nor #1375

You're right, I read through the issues again and noticed that there were about a different problem. But it does fix #1939.

**Pull request merged**
