### PR TITLE
change selected space highlight

### LINKED ISSUE #5346: Fix highlighting showing which Space is selected
On Android, the current Space is only highlighted with a green bar. Nique says that the designs show it as having a background highlighting as well.

This is done correctly on iOS.

### Tasks

- [x] @niquewoodhouse to attach link to figma/share design
- [ ] @fedrunov implement the design

### PR DESCRIPTION
**Pull request by fedrunov**
fixes #5346 

| Light theme  | Dark theme |
| ------------- | ------------- |
| image | image |

### CODE REVIEW

**Review by niquewoodhouse — APPROVED** [review]
@fedrunov just some questions to clarify some of the details, please. Looking between the designs and the build, I can see what you mean about differences.

- What's the size of the space avatars?
- What's the size of the space name next to the avatar?

It would be nice if these kind of details did match the design but I think making the details match could/should be a separate issue, so I'm approving this as it does change the highlight well while in keeping with the existing look/feel.

**Comment by fedrunov** [comment]
@niquewoodhouse 

Entire line (list item) height: 65dp
Avatar size: 42x42 dp
Space name text style: textSize = 16sp, leterSpacing = 0, textStyle=bold
Space description text style: textSize = 14sp, leterSpacing = 0, lineHeight = 20sp

**Comment by fedrunov** [comment]
I agree that  we need to file a separate PR to align current implementation with design in figma if we want to

**Comment by ouchadam** [comment]
to double check, these layours/drawables are used in other places, are we also okay for them to update?

**Review by bmarty — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
