### PR TITLE
rename zh-Hans and zh-Hant - TO BE MERGED DURING WEBLATE SYNC

### PR DESCRIPTION
**Pull request by ara4n**
as per https://github.com/vector-im/element-android/issues/2752

Want to get review from zh-experts before merging this though.

### CODE REVIEW

**Comment by eighthave** [comment]
Looks good!

**Comment by eighthave** [comment]
@linsui is who alerted us to this issue, they're the F-Droid `zh-Hans-CN` translator.  You can see clearly the tags that Google Play requires here: https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14

**Comment by eighthave** [comment]
You can see clearly that Google Play uses the dash `-` rather than `_`, but oddly, fastlane and Google Play seem to differ on the `zh` variants: https://support.google.com/googleplay/android-developer/table/4419860?hl=en

**Comment by bmarty** [comment]
Those files has been created by Weblate, so not sure if merging that will not mess up the next Weblate sync.
We should probably wait for https://github.com/WeblateOrg/weblate/issues/5522 to be fixed and released...

**Comment by eighthave** [comment]
I've already done some of these kinds of moves with projects in Weblate, it 
works fine.  Weblate is based on git, so it seems to inherit git's smooth 
handling of file renames.

**Comment by eighthave** [comment]
Also, the current names don't work properly with the `fastlane` tool nor 
F-Droid, so those trnaslations are already brken.

**Comment by bmarty** [comment]
Yes, it's broken, but what I want to avoid is having conflict when pulling from Weblate. I will merge this PR during the Weblate sync i.e. when Weblate is locked.

**Pull request merged**
