### PR TITLE
"Add space" copy is replaced with "create space" in left sliding panel

### PR DESCRIPTION
**Pull request by fedrunov**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other : misc

## Content

Android should use "Create space" in the left panel instead of "Add Space" because "adding" suggests other actions like joining an existing space.

## Motivation and context

https://github.com/vector-im/element-android/issues/5516

## Screenshots / GIFs

image

## Tests

- Login/Signup
- Open left slider
- Scroll to bottom
- Check copy

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): A12 (API 31)

## Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [x] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Review by ericdecanini — APPROVED** [review]
LGTM

**Comment by kittykat** [comment]
Ideally, the word Space should be lower cased so that it's "Create space". Is it possible to change that?

**Comment by ouchadam** [comment]
@kittykat yep it's a quick change to https://github.com/vector-im/element-android/blob/develop/vector/src/main/res/values/strings.xml#L2764

it's worth noting there are quite a few other strings which use "X Space", might be worth another ticket to update them all at the same time (would also mean we could merge this without the casing change)

**Comment by fedrunov** [comment]
capitalisation of space is changed in different PR: https://github.com/vector-im/element-android/pull/5539

**Pull request merged**
