### PR TITLE
Add dependency to opusencoder and remove module from this project

### LINKED ISSUE #6444: F-Droid build failed: Missing source code for binary files
1.4.26 adds several .so binaries: https://github.com/vector-im/element-android/tree/v1.4.26/library/opusencoder/src/main/cpp/opus/libs

The build instructions point directly to these binary files: https://github.com/vector-im/element-android/blob/v1.4.26/library/opusencoder/src/main/cpp/CMakeLists.txt

As per F-Droid policy, everything needs to built from source. Could you please provide build instructions for these files, so that the F-Droid build can be fixed? See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11270 for the current build recipe.

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other : Unblock release of the app from F-Droid

## Content

The lib have been externalized to https://github.com/vector-im/libopusencoder-android and is now published on MavenCentral. This PR remove the legacy module and a a dependency to the library from MavenCentral. This should allow F-Droid build to build the lib from source and then build Element Android from sources.

## Motivation and context

Closes #6444 

CC @TheLastProject

## Screenshots / GIFs

N/A

## Tests

- Send a voice message on API 23

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Review by ouchadam — APPROVED** [review]
assuming the CI is happy :crossed_fingers:

**Comment by bmarty** [comment]
Note that I tried to send a voice message on a API 28 emulator, but I get this toast: "Cannot record a voice message". Maybe due to the emulator configuration 🤔

**Comment by bmarty** [comment]
Lint is not happy too, locally it's fine, but I get those errors though:
```
> Task :vector:lintAnalyzeGplayDebug
e: /Users/bmarty/.gradle/caches/transforms-3/497dc14baa576c9944c1b5742d7fff01/transformed/jetified-opusencoder-1.0.0-debug/jars/classes.jar!/META-INF/opusencoder_debug.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/bmarty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.7.0/362da0b4951ed79a6591743a7fddcfb8c73809f6/kotlin-stdlib-jdk8-1.7.0.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/bmarty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.7.0/fbeaa8fa63cbab09c547083a449097be6660a9a/kotlin-stdlib-jdk7-1.7.0.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/bmarty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.0/a5f42c684ad9003160ef0d0f693ecf0ba7b13549/kotlin-stdlib-1.7.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/bmarty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.0/51736992f422993a1e741051bdf3c12801bc1ca1/kotlin-stdlib-common-1.7.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
```

I am wondering if we can do something about the first one, even if it seems to use a more recent version of metadata. (so the pb is on element android?)

**Comment by bmarty** [comment]
> voice messages are working as expected for me on my Pocofone f1 - API 29

Good to know, thanks. But on API 29 the app does not use the opusencoder library, since OGG is natively supported.

**Comment by bmarty** [comment]
Closing and reopening to trigger a new GHA round

**Comment by bmarty** [comment]
From @jmartinesp :

- need to change the package name [here](https://github.com/vector-im/libopusencoder-android/blob/main/opusencoder/src/main/cpp/opuscodec.cpp) in each function signature. It would be great to also change it in the README.
- to easily test in on a device with API >= Q we can override VoiceRecorderProvider to always return the L version. We could also add a `VectorFeatures` to force using the library at runtime. I will do that.

**Comment by bmarty** [comment]
To track, we will need to target opusencoder 1.0.1 which will be built with https://github.com/vector-im/libopusencoder-android/pull/1

**Comment by bmarty** [comment]
OK, sending voice message is working fine on API 29, even when forcing to use the (new v1.0.1) opusencoder library.

**Comment by bmarty** [comment]
Adding Z-NextRelease label since it's unblocking F-Droid release.

Still have an issue about lint...

**Pull request merged**
