### PR TITLE
Fix date format for some Asian languages (#1928)

### PR DESCRIPTION
**Pull request by yh-gao**
With DateFormat.getBestDateTimePattern to generate best localized pattern.

Signed-off-by: Yihong Gao <yihong.ui@gmail.com>

### Pull Request Checklist

- [X] Changes has been tested on an Android device or Android emulator with API 21
- [X] UI change has been tested on both light and dark themes
- [X] Pull request is based on the develop branch
- [X] Pull request updates [CHANGES.md](https://github.com/vector-im/element-android/blob/develop/CHANGES.md)
- [X] Pull request includes screenshots or videos if containing UI changes

Locale | EN | JP | zh_CN 
--- | --- | --- | ---
Screen Shot With Fix | en_US | JP | zh_CN

- [X] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by bmarty** [comment]
Thanks for the PR @yh-gao !

I have to trust you for the result in Asian language :)

Does it make sense to apply the same change to `messageHourFormatter` above in the code? It's the one other occurence of `DateTimeFormatter.ofPattern()` call.

**Comment by bmarty** [comment]
And also I assume this PR fixes #1928

**Comment by yh-gao** [comment]
> Thanks for the PR @yh-gao !
> 
> I have to trust you for the result in Asian language :)
> 
> Does it make sense to apply the same change to `messageHourFormatter` above in the code? It's the one other occurence of `DateTimeFormatter.ofPattern()` call.

NO, hour formatter no issues there and may not need fix.

**Comment by yh-gao** [comment]
> And also I assume this PR fixes #1928

Exactly!

**Pull request merged**
