### PR TITLE
Support Android 11 Conversation features

### PR DESCRIPTION
**Pull request by dkter**
Resolves the first item in #1722 

Screenshots:
Screenshot_20200725-133126
Screenshot_20200725-133145
Screenshot_20200725-133218

### Pull Request Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [x] No in-app UI change
- [x] Pull request is based on the develop branch
- [x] Pull request updates [CHANGES.md](https://github.com/vector-im/riotX-android/blob/develop/CHANGES.md)
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

Signed-off-by: David Teresi <dkteresi@gmail.com>

### CODE REVIEW

**Comment by BillCarsonFr** [comment]
Hello, thx for the contribution!
Does this PR include the floating bubble feature? that opens a floating chat?

**Comment by dkter** [comment]
@BillCarsonFr No, but it will be possible in the future after this PR. I've begun experimenting with the bubble feature but thought this should go through first.

**Comment by johns2s** [comment]
Any update on this?

**Comment by dkter** [comment]
> 
> 
> Any update on this?

It looks like sharing shortcuts have been added to Element since I wrote this PR, so that should probably be taken into account before this is merged (though I won't have time to work on it for at least a couple weeks.)

**Comment by bmarty** [comment]
Android 11 is now properly handled (see #2600 ), this PR should probable be updated after a rebase.

**Comment by dkter** [comment]
Sorry this took so long. I've updated this to work better with the API 30 target and stable Conversations API.

Here are a few other things I changed:
* Shortcuts (on the home screen, as well as for sharing) are no longer restricted to being favourited rooms only. This is because conversation notifications need to be associated with a shortcut, so shortcuts must be created for all rooms. I've replaced this with a ranking where favourited rooms are ranked higher than normal or low-priority rooms (so they will be prioritized to appear on the home screen, for example).
* I'm making sure the shortcut icon is cropped to a square because otherwise it doesn't render correctly in conversation notifications
* Previously, shortcut icons were being cropped because the app didn't account for Android's automatic 18dp crop for adaptive icons. I added a transparent border around shortcut icons to account for this

**Comment by dkter** [comment]
Some updated screenshots now that Android's conversation UI has finalized (and the icon crop has been fixed)

Conversation notification
Conversation settings

(note that shortcut icons like the ones below were previously cropped)

**Review by andrewaylett — APPROVED** [review]
I have rebased these changes on top of `develop` and run them locally on my OP6 with Android 11, and very much approve.

**Comment by HammyHavoc** [comment]
Reporting this on behalf of @bryandesrosiers, after upgrading to 1.2.1, which tagged this PR.

image

'Chatheads' ala Messenger would be awesome. :- )

**Comment by andrewaylett** [comment]
Odd, I see priority levels but not chat heads (because that's not implemented yet).  I've got most of the way to an implementation myself: enough to see the pop-out icon in the notification, but not to _actually show the chat_ when one taps on it.  Bit stuck now.  Anyone know if there's a specific bug for the remaining pieces that I could tag on to?

**Comment by dkter** [comment]
> enough to see the pop-out icon in the notification, but not to actually show the chat when one taps on it.

@andrewaylett I had this exact issue a year ago when I was trying my hand at implementing bubbles. No idea why it doesn't work, and I hadn't been able to find any other instances of this problem, though bubbles were a very new feature back then.

**Pull request merged**
