### PR TITLE
Avoid manual line breaks in exit onboarding dialog copy

### LINKED ISSUE #6087: Update exit FTUE copy formatting
Update the exit registration copy formatting to match iOS

| ANDROID | IOS |
| --- | --- |
image|image

### PR DESCRIPTION
**Pull request by ouchadam**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other : Copy

## Content

Fixes #6087 Updates the copy formatting to match iOS (android/material avoids centered text in dialogs) 

- Doesn't update script based languages as I'm not sure how the sentence should be structured.

## Motivation and context

To match iOS

## Screenshots / GIFs

|Before|After|
|-|-|
|Screenshot_20220601_150551|Screenshot_20220601_145612|

## Tests

- Start creating an account (after submitting username/password)
- Press back

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 28

### CODE REVIEW

**Comment by ouchadam** [comment]
checked in with design and got the :+1:

**Review by bmarty — CHANGES_REQUESTED** [review]
LGTM, but blocking the PR since it has to be merged only during the time Weblate is locked, to avoid painful merge conflict with Weblate.

**Review by ericdecanini — APPROVED** [review]

**Comment by bmarty** [comment]
I added the Z-NextRelease label to think about this PR when we will prepare the next release.

**Comment by ouchadam** [comment]
weblate is locked, will merge

**Pull request merged**
