### PR TITLE
Attachment Picker UI Improvements

### PR DESCRIPTION
**Pull request by onurays**
[Figma](https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=2039%3A26421)

@gaelledel: I had to reuse existing audio and contact icons. 

EDIT Benoit:

*Previous record removed (commented)*

Latest version:

attachment

### CODE REVIEW

**Comment by bmarty** [comment]
I have added two commit to fix an issue with some dimens, and add a rotation animation for the attachment button.

**Review by bmarty — APPROVED** [review]
LGTM

**Comment by gaelledel** [comment]
@onurays Could you provide a test build please?

**Comment by bmarty** [comment]
@gaelledel you can get the latest develop (since this PR has been merged) build at https://buildkite.com/matrix-dot-org/element-android/builds?branch=develop

**Comment by gaelledel** [comment]
@bmarty @onurays Can we remove the audio button (headphones) and simply get users to fetch audio via the attachment button? The bar is getting crowded with new functionalities and there is no immediate use case to resurface audio as a specific key action.

**Pull request merged**
