### PR TITLE
Use Context#getSystemService extension function provided by core-ktx.

### PR DESCRIPTION
**Pull request by johnjohndoe**
- Here the `Context#getSystemService` extension function is used which is provided by the `core-ktx` artifact.
- Sources: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/core/core-ktx/src/main/java/androidx/core/content/Context.kt#30

Signed-off-by: Tobias Preuss tobias.preuss@googlemail.com

---

_Feel free to rebase the branch before merging it to facilitate a linear history. Let me know if I should do this._

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Rebased and rebase conflicts resolved.

**Comment by johnjohndoe** [comment]
Rebased once more.

**Comment by johnjohndoe** [comment]
Rebased and rebase conflicts resolved.

**Comment by bmarty** [comment]
FTR I have added a c ommit (on develop) to ensure that we will always use this facility: 7b017e4328a00f0b7c0061581207ae7e1ba98ec5

**Comment by johnjohndoe** [comment]
Ah! Nice. That is a good idea. Thank you.

**Pull request merged**
