### PR TITLE
Add tooltip to explain what are the actions behind the icons

### PR DESCRIPTION
**Pull request by bmarty**
picker_tooltip

### CODE REVIEW

**Review by gaelledel — COMMENTED** [review]
Approved given we're changing the copy that appears to the following:

- image: Send images and videos
- sticker: Send sticker
- attachment: Upload file
- Polls: Create poll
- Camera: Open camera
- Contacts: Open contacts

**Review by gaelledel — APPROVED** [review]

**Comment by bmarty** [comment]
@gaelledel what is the wording for send audio?
image

Maybe just remove this item has it does not have a big added value compare to "files". WDYT?

**Comment by gaelledel** [comment]
Yes, I actually asked in here earlier https://github.com/vector-im/element-android/pull/4823 
"Can we remove the audio button (headphones) and simply get users to fetch audio via the attachment button? The bar is getting crowded with new functionalities and there is no immediate use case to resurface audio as a specific key action."

So if we could remove this audio item, that'd be grant!

**Comment by bmarty** [comment]
After update:

picker_tooltip

**Comment by AnisTaluqdar** [comment]
When tapping on the plus button there has an animation issue. @bmarty can you check it?

**Comment by bmarty** [comment]
@AnisTaluqdar which issue? Can you explain?

**Comment by AnisTaluqdar** [comment]
Outside the circle. Seems a box is rotating. I think it is not intentional.

**Comment by bmarty** [comment]
@AnisTaluqdar I see, thanks. It's due to the fact that we are using a PopupWindow to display this View. I am not sure how we can quickly avoid this side effect. Happy to hear some ideas.
Merging this PR for now.

**Pull request merged**
