### PR TITLE
Remove redundant heading from bug report issue form

### PR DESCRIPTION
**Pull request by opusforlife2**
### Pull Request Checklist

- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog

The issue form currently generates a bug report that contains the "What happened?" heading twice. See https://github.com/vector-im/element-android/issues/4047#issue-1001300890. This splits the two questions off into their own (compulsory) text boxes.

### CODE REVIEW

**Comment by opusforlife2** [comment]
This PR doesn't need the CI checks. Changes to peripheral files, like issue templates, can be made to be ignored by the CI. See https://github.com/TeamNewPipe/NewPipe/pull/6789.

**Comment by bmarty** [comment]
This is the opposite PR of https://github.com/vector-im/element-android/pull/3960.
Please see the discussion there about why we made it.

**Comment by kittykat** [comment]
Indeed, I prefer to have two sections but we compromised on one section to encourage all developers to fill in the issues in the same way that they would like users to do. Please feel welcome to propose better wording for one section. We want to explicitly prompt the issue filer to tell us what they were expecting and what happened.

(Also the ### need to be changed to ####)

Once we settle on wording, the same updates will need to be made against element-web (web and desktop templates) and element-ios

**Comment by opusforlife2** [comment]
Ah. Oops. I missed that PR.

I'll open a new one without splitting the textarea. 👍

**Comment by opusforlife2** [comment]
New PR #4076.

**Pull request closed without merging**
