### PR TITLE
Feature/verify one session

### LINKED ISSUE #1901: Do not propose to verify session if there is only one session
From the sessions list:

image

### PR DESCRIPTION
**Pull request by bmarty**
First commits are some cleanup.

Last commit fixes #1901: If there is no other session available, we do not propose to verify it:

## When other sessions are available (so no change by this PR)

image

## When no other sessions are available

image

### CODE REVIEW

**Review by BillCarsonFr — CHANGES_REQUESTED** [review]
As discussed we should show option to enter 4S passphrase if available (even if no other session, you can still verify). The existing verify button is showing this option, we will lose it of we remote it

**Comment by bmarty** [comment]
User can now verify the session if there is no other session, but 4S is configured

**Review by BillCarsonFr — APPROVED** [review]
LGTM. 
We need a new issue, to allow user to reset cross signing if he has no way to recover

**Comment by bmarty** [comment]
(#2052)

**Pull request merged**
