### PR TITLE
Fix wrong status of live location sharing in timeline (PSF-1073)

### LINKED ISSUE #6209: [Location share] - Live is considered as ended while running
### Steps to reproduce

To reproduce (see the video below). The problem is that when we come back to app after removing it from the stack, the live is considered as ended in timeline while it is still running. On other device it is still considered as running.

https://user-images.githubusercontent.com/46314705/171189694-7176c173-c7b6-45b5-9159-6d0591944cee.mp4

#### What did you expect?
The live should be considered as active.

#### What happened instead?
The live is considered as ended.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Fix in the aggregation process to avoid scheduling deactivation worker too many times and when not necessary.

## Motivation and context

Closes #6209 

## Screenshots / GIFs

|Before|After|
|-|-|
|<video src="https://user-images.githubusercontent.com/46314705/171189694-7176c173-c7b6-45b5-9159-6d0591944cee.mp4"/>|<video src="https://user-images.githubusercontent.com/46314705/171194021-2b0d43e2-2ee3-4aa2-8d75-a64c74bdb0b3.mp4"/>|  

## Tests

- Enable location sharing in Settings -> Preferences
- Enable live location sharing in Settings -> Labs
- Go to a room
- Start a live location share
- Remove the app from the stack of opened app
- Go back to the app
- Go to the room timeline where the live is running
- Check the live is still considered as running 

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 12

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Comment by onurays** [comment]
I don't understand the root cause of the problem and I cannot reproduce it.

**Comment by mnaturel** [comment]
> I don't understand the root cause of the problem and I cannot reproduce it.

To explain, I strongly suspect the fact we were relying on the remote value of the isActive field of the remote state event. When coming back to app, it was leading to trigger many workers to deactivate the live in local DB with a delay of 0.

**Review by onurays — APPROVED** [review]
Good catch! For other reviewers; other devices may be offline after starting to share their location and cannot update their status as `isLive=false` when sharing timed out.

**Review by bmarty — APPROVED** [review]
LGTM

**Pull request merged**
