### PR TITLE
Fixed dependabot

### LINKED ISSUE #5961: Dependabot does not upgrade all our dependencies.
According to https://github.com/vector-im/element-android/network/updates/361179500

Every dependencies are searched in https://jitpack.io/ and [https://github.com:443/vector-im/jitsi_libre_maven/raw/main/android-sdk-5.0.2](https://github.com/vector-im/jitsi_libre_maven/raw/main/android-sdk-5.0.2) on not mavencentral

For instance about `com.airbnb.android:mavericks` (extract of the link above):

> updater | INFO <job_361179500> Checking if com.airbnb.android:mavericks 2.5.0 needs updating
  proxy | 2022/05/05 23:09:41 [096] GET https://jitpack.io:443/com/airbnb/android/mavericks/maven-metadata.xml
  proxy | 2022/05/05 23:09:41 [096] 404 https://jitpack.io:443/com/airbnb/android/mavericks/maven-metadata.xml
  proxy | 2022/05/05 23:09:42 [098] GET https://github.com:443/vector-im/jitsi_libre_maven/raw/main/android-sdk-5.0.2/com/airbnb/android/mavericks/maven-metadata.xml
  proxy | 2022/05/05 23:09:42 [098] * authenticating git server request (host: github.com)
  proxy | 2022/05/05 23:09:42 [098] 404 https://github.com:443/vector-im/jitsi_libre_maven/raw/main/android-sdk-5.0.2/com/airbnb/android/mavericks/maven-metadata.xml
  proxy | 2022/05/05 23:09:42 [098] * auth'd git request returned 404, retrying without auth
updater | INFO <job_361179500> Latest version is 
updater | INFO <job_361179500> Requirements to unlock update_not_possible
updater | INFO <job_361179500> Requirements update strategy 
updater | INFO <job_361179500> No update possible for com.airbnb.android:mavericks 2.5.0

But Maverick 2.6.1 exists, see https://github.com/airbnb/mavericks/releases, and https://repo1.maven.org/maven2/com/airbnb/android/mavericks/2.6.1/

I think we have lots of outdated dependencies now.

Tentative fix from @ouchadam, by reordering our dependencies repositories : fd2aaa8c2bfa669f48309477e11f32659eb54e5d . But no effect :/

Not sure how to fix this annoying issue :/

### PR DESCRIPTION
**Pull request by MarcelCoding**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other : fixed dependabot, closes #5961 

## Content

Changed gradle dependency decleration from:
```groovy
mavenCentral()
```
to
```groovy
maven { url 'https://repo1.maven.org/maven2' }
```

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

probably squash this pr

Signed-off-by: Marcel <34819524+MarcelCoding@users.noreply.github.com>

### CODE REVIEW

**Comment by bmarty** [comment]
Thanks for the PR (and for founding the workaround!)! I am also working on #5967.

**Review by bmarty — APPROVED** [review]
Thanks for the PR. I will merge it and rebase mine 👍

**Comment by bmarty** [comment]
FTR, post merge effect:

image

**Comment by MarcelCoding** [comment]
now you have some work xd

**Pull request merged**
