### PR TITLE
Correct public_baseurl for nightly tests.

### PR DESCRIPTION
**Pull request by michaelkaye**
The tests seem to function against a synapse with an incorrect public_baseurl - some parts of the client use the public_baseurl for information and timeout, others use the configured http endpoint (which is hardcoded in the tests to be correct).

Making this change reduces timeouts waiting for requests to these incorrect endpoints.

### CODE REVIEW

**Comment by michaelkaye** [comment]
So the change in fb19d6b seems to have been powerful in itself; the baseurl was wrong for a number of the tests (compared to running locally).

**Review by bmarty — COMMENTED** [review]
LGTM so far (the PR is still a draft)

**Comment by michaelkaye** [comment]
We may as well merge this as-is.

**Review by ouchadam — APPROVED** [review]

**Comment by ouchadam** [comment]
I have this change locally as it's needed for the sanity tests to login in after creating an account

**Pull request merged**
