### PR TITLE
store cache for WidgetWebView between loads

### PR DESCRIPTION
**Pull request by dkanada**
The sticker widget is extremely inefficient due to these lines, reloading every asset on the page any time the sticker widget is opened. I made a new sticker widget and made this change on my personal builds to avoid ten second load times every time I wanted to send a sticker. This should only cause issues for widgets hosted on servers that don't properly invalidate caches as far as I can tell, but the WebView cache can also be manually reset with the `Reset Cache` option in the app settings.

### CODE REVIEW

**Comment by dkanada** [comment]
Are there any specific issues with this pull request or is it just a low priority? I'll just close it if there are concerns with other widgets or something.

**Comment by bmarty** [comment]
Thanks for the PR. To be honest, I'm not sure about the impact with other widget, or even with the sticker widget.
@ganfra WDYT?

**Comment by Bubu** [comment]
This would fix #2066 if merged.

**Review by bmarty — APPROVED** [review]
Let's merge the PR, I'll add a file for towncrier on develop. Thanks @dkanada !

**Comment by bmarty** [comment]
Done in  8a38f1ca04af7897d354236520802a347ebba2c6

**Pull request merged**
