### PR TITLE
Improve issue automation workflows

### LINKED ISSUE #4617: Improve issue automation workflows
- Fix filtering for Design issues
- Split out spaces jobs for new and old boards, so they don't depend on each other
- Improve naming for jobs so they're easier to read in the GitHub Actions page

### PR DESCRIPTION
**Pull request by kittykat**
Fixes #4617

### Pull Request Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Comment by kittykat** [comment]
Please "Rebase and merge" to keep the commits logical and the details from the descriptions.

**Review by bmarty — APPROVED** [review]
LGTM

**Comment by kittykat** [comment]
@bmarty I've ended up without write access to the repo, I think based on current settings I'd need to be in the Android team to be able to merge PRs!

**Comment by bmarty** [comment]
> @bmarty I've ended up without write access to the repo, I think based on current settings I'd need to be in the Android team to be able to merge PRs!

Your in the Android team now.

**Pull request merged**
