### PR TITLE
Fix cleartext leak in log

### PR DESCRIPTION
**Pull request by SpiritCroc**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

Signed-off-by: Tobias Büttner <dev@spiritcroc.de>

### CODE REVIEW

**Comment by ouchadam** [comment]
great catch! will pull into the 1.4.31 release

**Review by ouchadam — APPROVED** [review]

**Comment by jellykells** [comment]
No security advisory for this?

**Comment by bmarty** [comment]
> No security advisory for this?

This are `Event` for verification request, so they should not contains any personal messages. I will ask the security team for a confirmation though.

**Comment by ouchadam** [comment]
it's also a debug log which requires `developer mode enabled -> enable verbose logging`

**Comment by SpiritCroc** [comment]
I've seen personal message content come in from this over rageshake in SchildiChat. The user also claimed to not have "verbose logging" enabled :shrug:

**Pull request merged**
