### PR TITLE
[Device management] Sign out a session (PSG-742)

### LINKED ISSUE #7190: [Device management] Sign out a session
#### What would you like to do?
Add the ability to sign out a session in the new device management screens (only in session overview screen for now).

#### Why would you like to do it?
User should be able to sign out from a given session.

#### How would you like to achieve it?
https://www.figma.com/file/jI0ZdCeKKa51BDORmXdnRU/Settings%3A-UI-Refresh?node-id=893%3A50795

### Have you considered any alternatives?

_No response_

### Additional context

_No response_

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by mnaturel**
## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Adding a signout button in the session overview screen.

## Motivation and context

Closes #7190 

## Tests

- Enable the feature flag for new device management
- Go to Settings -> Security & Privacy -> Show all sessions (WIP, V2)
- Press a session item to go to the corresponding session overview screen
- Press the signout button
- Check reauth is asked if needed
- Check the screen is exited after signout is done
- Check the session has disappeared from the screens
- Try the same process with the current session
- Check the app is restarted in this case

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): Android 11

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Review by jmartinesp — APPROVED** [review]
LGTM!

**Comment by mnaturel** [comment]
To improve it, we need to add a confirmation dialog when trying to sign out another session like for the current session.

**Comment by mnaturel** [comment]
@jmartinesp I have added a confirmation dialog for all session types since it is a destructive operation. You can see it here: [082fa1e](https://github.com/vector-im/element-android/pull/7243/commits/082fa1e69ee884f766975b08db420fbbfeb07713)

**Comment by jmartinesp** [comment]
The last change seems to be working fine and the code makes sense. It feels a bit weird to have a `SignOutUiWorker` that's not shared for sign out from current session and sign out from other sessions, but it's not a blocker.

**Comment by mnaturel** [comment]
> The last change seems to be working fine and the code makes sense. It feels a bit weird to have a `SignOutUiWorker` that's not shared for sign out from current session and sign out from other sessions, but it's not a blocker.

Yes I am also concerned about that (especially because it is not easily testable right now) but that would mean to refactor all the signout of current session process. I didn't want to start this work in this PR.

**Pull request merged**
