### PR TITLE
Image compression

### PR DESCRIPTION
**Pull request by bmarty**
Co-author: Onuray :)

Will be merged after #1889 of course

Remove dependency to a Compression library and do the stuff by ourselves.

### CODE REVIEW

**Review by onurays — APPROVED** [review]
Looks very good to me :) 💯

**Comment by bmarty** [comment]
I'm working on rebasing it FTR

**Review by BillCarsonFr — APPROVED** [review]
LGTM

**Comment by bmarty** [comment]
Will be merged when CI is happy

**Pull request merged**
