### PR TITLE
Allow integration tasks to fail, but use if: always() to allow the next step to continue anyway.

### PR DESCRIPTION
**Pull request by michaelkaye**
Move from `continue_on_error` to `if: always()`.

This will allow previous steps to explicitly fail and be marked as failed
but later steps will continue to run in order to display the outcomes.

(there's probably a better way to do this, but this will at least start
to expose the errors in the UI)

 
## Type of change

- [ ] Feature
- [ ] Bugfix
- [x] Technical
- [ ] Other :

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Comment by michaelkaye** [comment]
https://github.com/vector-im/element-android/runs/5308306149?check_suite_focus=true#step:13:275

What in the world is taking 60min here. Needs some investigation for sure.

**Comment by michaelkaye** [comment]
The investigation will be made easier with the timing data in #5339 but this PR i believe can be merged anyway; the slow test run isn't directly related to this change.

**Review by bmarty — APPROVED** [review]
LGTM

**Comment by michaelkaye** [comment]
I have additionally disabled the requirement for the integration checks to be green before merging a branch; this would otherwise block a lot of merges until we fix the underlying issues.

**Review by ariskotsomitopoulos — COMMENTED** [review]
Seems fine to me

**Pull request merged**
