### PR TITLE
Update reactions to Unicode 13.1, improve backwards compatibility

### PR DESCRIPTION
**Pull request by oogm**
### Pull Request Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 21
- [x] UI change has been tested on both light and dark themes
- [x] Pull request is based on the develop branch
- [x] Pull request updates [CHANGES.md](https://github.com/vector-im/element-android/blob/develop/CHANGES.md)
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

### Summary
This PR introduces two things:
1) Updates the emoji_picker_datasource.json from Unicode 10 to Unicode 13.1.
It does this with the script included below, so updating Unicode to newer versions in the future should be as easy as launching this script against newer versions on Unicode.org. This fixes issue #1481.

2) Instead of just displaying all Emojis in the Picker, it checks if they can be rendered on the user's version of Android first. This greatly improves the experience on old devices (see screenshots).

``Signed-off-by: Benjamin Löhner <ga84dom@mytum.de>``

### Screenshots:
Note how non-renderable glyphs in API 21 are filtered correctly and how newer versions of Android contain up-to-date emojis as mentioned in issue #1481
Screenshots-small

### Update script:
This is the script used to pull emojis from Unicode.org and convert it into the required json-format:
```python3
import requests
import json
import re
from bs4 import BeautifulSoup

# Create skeleton of the final json file as a python dictionary:
emoji_picker_datasource = {
    "compressed": True,
    "categories": [],
    "emojis": {},
    "aliases": {}
}
emoji_picker_datasource_categories = emoji_picker_datasource["categories"]
emoji_picker_datasource_emojis = emoji_picker_datasource["emojis"]


# Get official emoji list from unicode.org (Emoji List, v13.1 at time of writing)
req = requests.get("https://unicode.org/emoji/charts/emoji-list.html")
soup = BeautifulSoup(req.content, 'html.parser')

# Navigate to table
table = soup.body.table

# Go over all rows
for row in table.find_all('tr'):
    # Add "bigheads"  rows to categories
    if 'bighead' in next(row.children)['class']:
        relevant_element = row.find('a')
        category_id = relevant_element['name']
        category_name = relevant_element.text
        emoji_picker_datasource_categories.append({
            "id": category_id,
            "name": category_name,
            "emojis": []
        })

    # Add information in "rchars" rows to the last encountered category and emojis
    if row.find('td', class_='code'):
        # Get columns
        cols = row.find_all('td')
        no_element = cols[0]
        code_element = cols[1]
        sample_element = cols[2]
        cldr_element = cols[3]
        keywords_element = cols[4]

        # Extract information from columns
        # Extract name and id
        # => Remove spaces, colons and unicode-characters
        emoji_name = cldr_element.text
        emoji_id = cldr_element.text.lower()
        emoji_id = re.sub(r'[^A-Za-z0-9 ]+', '', emoji_id, flags=re.UNICODE)  # Only keep alphanumeric, space characters
        emoji_id = emoji_id.strip()  # Remove leading/trailing whitespaces
        emoji_id = emoji_id.replace(' ', '-')

        # Extract emoji unicode-codepoint
        emoji_code_raw = code_element.text
        emoji_code_list = emoji_code_raw.split(" ")
        emoji_code_list = [e[2:] for e in emoji_code_list]
        emoji_code = "-".join(emoji_code_list)

        # Extract keywords
        emoji_keywords = keywords_element.text.split(" | ")

        # Add the emoji-id to the last entry in "categories"
        emoji_picker_datasource_categories[-1]["emojis"].append(emoji_id)

        # Add the emoji itself to the "emojis" dict
        emoji_picker_datasource_emojis[emoji_id] = {
                "a": emoji_name,
                "b": emoji_code,
                "j": emoji_keywords
        }

# Print result to stdout, without escaping unicode characters
print(json.dumps(emoji_picker_datasource, ensure_ascii=False))
```

### CODE REVIEW

**Comment by bmarty** [comment]
Thanks for the PR, it looks good to me.

2 points:
- Can you add the script as part of this PR to the project? Maybe at `./tools/import_emojis.py`. The script could directly overwrite to file `./vector/src/main/res/raw/emoji_picker_datasource.json`
- How do you take screenshots with full height like that? It looks very useful.

**Review by bmarty — APPROVED** [review]
See my comment above

**Comment by oogm** [comment]
Thanks for the approval! I've added the script as a file.
Reg. the screenshots: I just found 40 screenshots too hard to read, so I manually stitched them together. I've shortly looked into it, but seems like long screenshots are not really supported on AOSP-based android.

Do we want to link issue #1481? I think it would be resolved by this PR.

**Comment by oogm** [comment]
Also I think the CI failed because of a short JCenter outage that (according to the website) should be resolved now, so if re-ran it should pass without requiring a change to this PR :)

**Comment by bmarty** [comment]
Thanks for the update.
I've asked the CI to build again.

**Comment by oogm** [comment]
Awesome, that did the job. Thanks!

**Comment by bmarty** [comment]
There is a regression when we want to display completion in room. We should display the 8 quick reaction, but with this change, only 2 are displayed:

image

and before (ignore theme diff):

image

[This list](https://github.com/oogm/element-android/blob/e8015bfbd4f8e24faa0fd21917b150defcb17a82/vector/src/main/java/im/vector/app/features/reactions/data/EmojiDataSource.kt#L102) should have to be updated. Can you handle that please?

Also we can see that there is much less words which matches the emoji, so emoji completion using words will be less powerful. Is there a way to improve that?

**Review by bmarty — CHANGES_REQUESTED** [review]
(small regression in emoji completion)

**Comment by oogm** [comment]
Thanks a lot for testing and flagging this!

I've adapted the script to extend the emojis default keywords from Unicode.org with keywords from the popular and well-maintained [emojilib-project](https://github.com/muan/emojilib). This should cover the previous keywords and even extend them, so I expect the emoji-search to be at least equally (but probably even more) powerful.

In addition I've updated the quick reactions as requested.

Let me know what you think :)

**Comment by github-tomster** [comment]
in relation to this https://github.com/vector-im/element-android/pull/2514 example how not to code 🤷‍♂️ 
resulting in that https://github.com/vector-im/element-android/issues/2944  bad experience 🤦‍♂️ 

will this PR also lead to a fail and ruin my emoji picker by not displaying **my** NotoColorEmoji.ttf emojis ❓ 🧙‍♂️

**Comment by oogm** [comment]
Hey @github-tomster,

I see your concern, thanks for checking in! 
#2514 actually changes the libraries used to display the emojis.
This change, however, does not touch any of this logic. It solely updates the list of emojis in the reactions picker from Unicode 10 to Unicode 13.1, and adds automation to make this process easier in the future.
This only changes the number of emojis that are displayed, but neither their rendering approach, nor the font which they are loaded from. I'm not sure how the rendering of reactions emoijs is done internally, but if they were taken from NotoColorEmoji.ttf before, they will still be taken from there after this change (refer to the screenshots above for a visual before-after this change demonstration that shows this).

**Comment by github-tomster** [comment]
hoi @oogm 
thx for the explanation, much appreciated 🙇‍♂️ 
and i like ur approach to cure the emoji 💩 👍 

it is so sad that it is even necessary to code something like this. 🤦‍♂️ 
looking at and suffering from the whole emoji desaster i try to use some of my free time and post some 🤯 
unfortunately #2514 shows how bad a user-experience can be wrecked 👿

**Comment by bmarty** [comment]
Hello @oogm ,

Thanks for the updates, it looks awesome!

I have new remarks, sorry for the iterating review:

1. Can you make the script executable? 
2. Can you make the script works when called from anywhere? You can get inspired by what we have in the script `import_sas_string.py` at line 89-90
3. Can you remove the extra space from the big json file (you can add parameter `separators=(',', ':')` to `json.dump()` call)
4. Can the values of each key "a" be capitalized? For instance, before it was "Party Popper", and now it's "party popper". Should be better to keep "Party Popper"
5. Can you move the new line in the changelog to the 1.1.4 section? This PR will be merged for release 1.1.4.

As a bonus, it should be great to echo some logs form the script, because it can take several minutes to be run on my computer, so it seems locked :)

I think this is my final remarks

Thanks!

**Comment by oogm** [comment]
Hey @bmarty,
Thanks for the comments, nice attention to detail with the emoji name capitalization!
I have updated this PR to address all your remarks, please take a look.

**Review by bmarty — APPROVED** [review]
Wonderful, thanks for the update!

**Pull request merged**
