### PR TITLE
In TimelineForwardPaginationTest, explicitly test for the events we expect

### PR DESCRIPTION
**Pull request by michaelkaye**
This permits a clear error when the events are missing / extra and while
not making the test invulnerable to future changes in events, should be
explicit on what's changed.

 
## Type of change

- [ ] Feature
- [ ] Bugfix
- [X] Technical
- [ ] Other :

## Content

The test was failing with a count of 58 events not the expected 57. 

To diagnose why, I split out the events by type, and asserted each count individually.

I believe we've gained one state event of some type, but I don't know which one (as we didn't have historical information).

From now, the test will error with a quite specific reason (missing an event or found an event)

A similar issue was fixed in another pagination test (different style of test so splitting out checks by message type was harder)

## Motivation and context

Fix integration test

## Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 21
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR
- [ ] If you have modified the screen flow, or added new screens to the application, you have updated the test [UiAllScreensSanityTest.allScreensTest()](https://github.com/vector-im/element-android/blob/main/vector/src/androidTest/java/im/vector/app/ui/UiAllScreensSanityTest.kt#L73)

### CODE REVIEW

**Comment by michaelkaye** [comment]
I believe the "context" in the original comment that was removed was a single message - paginating back 50 should add another 50 to it; but i might be wrong - someone with knowledge of the original test might help here.

**Comment by michaelkaye** [comment]
I think something similar is happening in PreviousLastForwardTest (it is timing out waiting for there to be exactly X items in the snapshot, but there are x+1 or x-1)

**Comment by michaelkaye** [comment]
Original test failure:
```
org.matrix.android.sdk.session.room.timeline.TimelineForwardPaginationTest > forwardPaginationTest[test(AVD) - 9] FAILED 
	org.amshove.kluent.internal.ComparisonFailedException: Expected: <57> but was: <58>
	at org.amshove.kluent.internal.AssertionsKt.assertEquals(Assertions.kt:129)
```

**Comment by michaelkaye** [comment]
Looks like buildkite failure is unrelated

**Review by ericdecanini — APPROVED** [review]

**Comment by michaelkaye** [comment]
> Does buildkite let us rerun tests? There's a good chance I think that rerunning it would pass

It does, but i don't have access to do so. I'm fairly sure this isn't something I can have affected as buildkite doesn't touch any of the tests themselves.

**Pull request merged**
