### PR TITLE
Properly clean the back stack if the user cancel registration when waiting for email/msisdn validation

### PR DESCRIPTION
**Pull request by bmarty**

### CODE REVIEW

**Review by BillCarsonFr — APPROVED** [review]
LGTM

**Comment by DonutDev** [comment]
lmao, I posted a meme on reddit about Element and now it's fixed. Great stuff!

**Comment by bmarty** [comment]
I post the link for posterity: https://www.reddit.com/r/programminghorror/comments/n5h6px/was_trying_to_make_an_account_on_element/ :)

**Comment by bmarty** [comment]
Also, it's worth noting that this error comes from the Android Matrix SDK, and is supposed to help developers to implement correctly the registration flow. Which on this particular case was not OK :)

**Comment by bmarty** [comment]
Fixes #1403

**Pull request merged**
