### PR TITLE
Add Android Auto notification support

### PR DESCRIPTION
**Pull request by abaker**
### Pull Request Checklist

- [X] Changes has been tested on an Android device or Android emulator with API 21
- [X] UI change has been tested on both light and dark themes
- [X] Pull request is based on the develop branch
- [X] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [X] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by abaker** [comment]
This PR is for #240. It enables message notifications in Android Auto with mark as read and voice reply functionality.

In order to release this to the Play Store you have to click on `Advanced settings > Release types > Add release type > Android Auto > Accept the Android for Cars Terms of Service`

It seems like apps require some sort of entitlement granted by the Play Store to actually work on the Android Auto app or an Android Auto head unit. Debug builds will only work in the [Desktop Head Unit](https://developer.android.com/training/cars/testing#test-auto). I assume this also means the F-Droid build will not work with Android Auto.

**Review by ouchadam — APPROVED** [review]
LGTM :100: thanks for this! 

- double checked notification actions still work

**Comment by bmarty** [comment]
Thanks for the PR!

> In order to release this to the Play Store you have to click on Advanced settings > Release types > Add release type > Android Auto > Accept the Android for Cars Terms of Service

Taking care of this part with the legals

**Comment by bmarty** [comment]
T&C have been accepted:

image

Next step is to upload an APK, which will be done on the next release.

**Comment by thomcatdotrocks** [comment]
> This PR is for #240. It enables message notifications in Android Auto with mark as read and voice reply functionality.
> 
> In order to release this to the Play Store you have to click on `Advanced settings > Release types > Add release type > Android Auto > Accept the Android for Cars Terms of Service`
> 
> It seems like apps require some sort of entitlement granted by the Play Store to actually work on the Android Auto app or an Android Auto head unit. Debug builds will only work in the [Desktop Head Unit](https://developer.android.com/training/cars/testing#test-auto). I assume this also means the F-Droid build will not work with Android Auto.

Just an FYI for anyone reading this PR: Here's how you can get Android Auto working on a `dbg` build:

  · Enable Developer Mode in the Android Auto app.  Settings > Tap the "Version and permission info tab" until Developer Mode is enabled.
  · Allow Unknown sources.  Setings > 3 button menu > Developer settings > Check "Unknown sources".

image

**Comment by bmarty** [comment]
After APK 1.3.2 upload:

image

**Pull request merged**
