### PR TITLE
FTUE - Finalising personalisation journey

### LINKED ISSUE #5200: Mobile FTUE: Profile Personalisation screens (Android)
Android specific https://github.com/vector-im/element-meta/issues/132

- [x] Account created screen #5158 
- [x] Add support for additional homeserver capabilities (display name/avatar) #5208 
- [x] Choose a display name screen #5211
- [x] Add a profile picture screen #5323
- [x] Personalisation complete screen #5389
- [x] Avoid showing personalisation screens if the homeserver has disabled them #5375
- [x] Confirm error messaging and handling (local rules extracted to https://github.com/vector-im/element-meta/issues/204) #5517  
- [x] Enable feature - product/design sign off #5519 

Also:
- [ ] https://github.com/vector-im/element-meta/issues/132
- [x] https://github.com/vector-im/element-android/issues/5099

### PR DESCRIPTION
**Pull request by ouchadam**
Marked as draft as this relies on #5517

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Part of #5200 (will be fully closed once the feature is enabled) 

- Adds the personalisation steps to the UI Sanity tests
- Promotes the WIP strings to the main file, ready for translators to pick up

## Motivation and context

To promote and enable users to customise their account as soon as they sign up 

#### Pixel 4 XL

| 1 | 2 | 3 | 4 | 
| --- | --- | --- | --- | 
|after-tall-1|after-tall-2|after-tall-3|after-tall-4
after-1-l|after-2-l|after-3-l|after-l-4

#### Tiny device
| 1 | 2 | 3 | 4 |
| --- | --- | --- | --- |
|after-1-s|after-2-s|after-3-s|aftrer-4-s

#### Nexus 9 

| 1 | 2 | 3 | 4 |
| --- | --- | --- | --- |
|after-1-t|after-2-t|after-3-t|after-4-t
after-1-p|after-2-p|after-3-p|after-4-p

| PERSONALISATION ENABLED | PERSONALISATION DISABLED | ONLY DISPLAY NAME | ONLY PROFILE PICTURE |
| --- | --- | --- | --- |
|after-gif|after-disabled|after-only-dn|after-only-pp

## Tests

- Create a new account!

## Tested devices

- [x] Physical
- [x] Emulator
- OS version(s): 28, 29, 32 (Sv1)

### CODE REVIEW

**Comment by daniellekirkwood** [comment]
Watched the demo, it looks great.

**Comment by amshakal** [comment]
Looks great! Specially the implementation on small screens 👯‍♀️

**Review by amshakal — APPROVED** [review]

**Review by mnaturel — APPROVED** [review]
LGTM.

**Comment by ouchadam** [comment]
double checking with product if we want to enable the personalisation steps without the other FTUE changes

**Comment by ouchadam** [comment]
@mnaturel we've decided to keep the feature disabled in favour of enabling all the onboarding steps at the same time, there's some minor changes to take into account the feature flag state in the tests

**Review by mnaturel — APPROVED** [review]
Okay for me but I see there are some conflicts to handle before merging.

**Pull request merged**
