### PR TITLE
Change Encryption Trust Shield to align to Left of Avatars

### LINKED ISSUE #2051: Request: Move shields to the left side of room icons
**Is your feature request related to a problem? Please describe.**
Partly due to a confusion in design language, and partly to prepare for the upcoming #70 issue (presence management), I think the current position of the encryption shield on the right sides of avatars could be conflicting with common design language of the "online/offline indicator" in the rest of the industry, and even within element itself (see Element Web)

**Describe the solution you'd like**
Move the encryption shield to the left side of avatar/room icons, this is a "new spot" to put design elements in, it explicitly disassociates itself then with the "user status indicator" used in other applications, subtly signalling it's not a user status indicator, but something else just as important.

**Describe alternatives you've considered**
I previously considered removing the shield entirely in room lists (in anticipation of #70, to put the user presence indicator there), but I saw that moving it was a better alternative.

**Additional context**
I think clarifying the design language of the app in a way that doesn't conflict with other apps of its type (discord, telegram, itself (web), etc.) would be beneficial to better adoption and recognition of elements presented in the UI, such as the encryption shield representing the out-of-band user verification mechanism status, while 'excommunicating' it from user presence.

### PR DESCRIPTION
**Pull request by ShadowJonathan**
Additional changes are made to make sure layouts display shifted shields correctly

Closes #2051

### Pull Request Checklist

- [X] Changes has been tested on an Android device or Android emulator with API 21
- [X] UI change has been tested on both light and dark themes
- [X] Pull request is based on the develop branch
- [x] Pull request updates [CHANGES.md](https://github.com/vector-im/element-android/blob/develop/CHANGES.md)
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by bmarty** [comment]
Hello @ShadowJonathan , thanks for the PR, could you please add screenshots before/after your change?

It will help the design team to validate (or not) the changes.

Thanks

**Comment by ShadowJonathan** [comment]
@bmarty I will, i'm currently pre-occupied and stamped this WIP PR so i could remind myself at a later date to finish it, i have it planned to finish the checklist

**Comment by ShadowJonathan** [comment]
# Screenshots:

## Before

[Room Directory](https://user-images.githubusercontent.com/22740616/93308741-edb66c80-f802-11ea-9125-c09e9fd2ee13.png)

[Room](https://user-images.githubusercontent.com/22740616/93308780-fc9d1f00-f802-11ea-8505-0c99c0daefdb.png)

[Room Detail](https://user-images.githubusercontent.com/22740616/93308793-01fa6980-f803-11ea-9951-10d688ff4103.png)

[Room User List](https://user-images.githubusercontent.com/22740616/93308824-0e7ec200-f803-11ea-96df-bd45e1759e5b.png)

[User Profile](https://user-images.githubusercontent.com/22740616/93308841-16d6fd00-f803-11ea-84a1-05a92172e575.png)

## After

[*Room Directory*](https://user-images.githubusercontent.com/22740616/93306787-9ca57900-f800-11ea-8f7a-266cd68f47b0.png)

[*Room*](https://user-images.githubusercontent.com/22740616/93307004-d5dde900-f800-11ea-9737-d23b016c3aa2.png)

[*Room Detail*](https://user-images.githubusercontent.com/22740616/93307042-dc6c6080-f800-11ea-959f-2939668e8b69.png)

[*Room User List*](https://user-images.githubusercontent.com/22740616/93307092-e8f0b900-f800-11ea-92ca-e98bebd25133.png)

[*User Profile*](https://user-images.githubusercontent.com/22740616/93307124-ee4e0380-f800-11ea-8575-609e6c81b633.png)

Please tell me if there are any other areas where this shield is displayed in-app I'm unaware how to bring up.

**Comment by bmarty** [comment]
More easy view of the screenshots:

# Screenshots:

## Before

## Room Directory



## Room



## Room Detail


## Room User List



## User Profile



## After

## Room Directory



## Room



## Room Detail



## Room User List



## User Profile

**Review by nadonomy — CHANGES_REQUESTED** [review]
Hi @ShadowJonathan apologies this won't really be the news you'll be wanting to hear but we won't be able to merge this. I empathise greatly with the goals of the changes, but:

- The bottom left placement isn't congruent with how the eye scans for information which ends up making the whole app feel a little awkward to the eye
- More importantly, it creates cross-platform inconsistencies with iOS & the web on a security related feature— any change like this we would need to co-ordinate across all platforms to ensure a smooth transition for users

We'll be pouring some effort into presence soon on the core team (including iterating on all platforms, and on the server) and will definitely take into account your critical thinking and changes here then, but unfortunately won't be able to merge until we can tick all of the right boxes holistically.

Thanks for the PR though, and of course you're welcome to use the changes in your own fork!

**Comment by ShadowJonathan** [comment]
That's alright, I understand the reasoning, and I was mostly aiming for some awareness on this issue anyways.

Thanks for taking this PR into account, and i'd love to see presence come to Element :D

**Pull request closed without merging**
