### PR TITLE
Feature: add E2EE Url Preview Passthrough in the room settings

### PR DESCRIPTION
**Pull request by Baconxrp**
## Type of change

- [ x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

add E2EE Url Preview Passthrough that was recently added to the web/desktop version of element in the room settings to both android and ios.

It was a change that allowed the user on desktop/web to be able to go into an ENCRYPTED room and have a choice to be able to see url previews if they wish to.

## Motivation and context

The motivation is simple. I currently have EE2E URL preview passthrough on desktop/web when i talk to my friends at home and they send me links over dms and it is nice to see the preview on them that I chose to change the room setting on. I want to be able to also do this on my phone / mobile device.

Thank you!

## Screenshots / GIFs

Screenshot_36_20220326100057_20220327064415~2

### CODE REVIEW

**Comment by bmarty** [comment]
Hey @Baconxrp , thanks for your PR!

This diff is quite strange, can you ensure that the base branch is set to our `develop` branch?

Then we will be able to review it.

Thanks

**Comment by Baconxrp** [comment]
> Hey @Baconxrp , thanks for your PR!
> 
> This diff is quite strange, can you ensure that the base branch is set to our `develop` branch?
> 
> Then we will be able to review it.
> 
> Thanks

Sorry, im unsure how to do that. Im just putting this out there as an individual who runs a matrix server and hasn't federated yet because this feature hasn't been fully implemented across all platforms. Been running our server for close to two years now. Hopefully it comes out so we can federate.

**Comment by Baconxrp** [comment]
So schildichat on android already has this feature in the beta.
Screenshot_20220503-151139
Screenshot_20220503-151418

Hopefully it comes over to element soon.

**Comment by bmarty** [comment]
Sorry, there is a pb with this PR, please create it again

image

**Pull request closed without merging**
