### PR TITLE
Fix zero values for uploaded image dimmensions when uploaded as a File #1628

### PR DESCRIPTION
**Pull request by SPK44**
The PR fixes issue #1628, and cleans up some code related to the MultiPicker at the same time. 

The original bug was caused by an image being created as a MultiPickerFileType when it was selected in the File menu. At no point the image dimensions were updated from default of zero, unless the image was compressed.

The fix I implemented was to have the File MultiPicker dynamically create an image, audio, video, or file object based on the mime type.

### Pull Request Checklist

- [x] Changes has been tested on an Android device or Android emulator with API 16
- [x] UI change has been tested on both light and dark themes
- [x] Pull request is based on the develop branch
- [x] Pull request updates [CHANGES.md](https://github.com/vector-im/riotX-android/blob/develop/CHANGES.md)
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)

Signed-off-by: Douglas Deslauriers <DeslauriersDouglas@gmail.com>

### CODE REVIEW

**Comment by delbonis** [comment]
Someone should also submit a PR to the iOS app to make it not blindly trust the `w` and `h` fields and to update the UI when the image is fully loaded.

**Comment by SPK44** [comment]
I should note that no UI changes have been made

**Comment by SPK44** [comment]
@bmarty I was cleaning up a merge conflict to prepare for review, and there seems to be an issue with a missing `olm.jar` in CI. Can you verify that this is a CI issue, or let me know if this is an issue I need to take care of?

**Comment by bmarty** [comment]
@SPK44 do not worry this issue will be fixed by itself

**Comment by SPK44** [comment]
I just realized that you use rebasing the develop branch onto feature branches rather than making merge commits. I have opened a new pull request #2068 to track this instead. It is ready for review

**Pull request closed without merging**
